version: '2'
services:
    autodiscovery:
        build: ./autodiscovery/
        mem_limit: 128m
        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500
        ports:
            - 8500:8500
        dns:
            - 127.0.0.1

    microservice_base_fpm:
        build: ./microservices/base/php-fpm/
        links:
            - autodiscovery
        expose:
            - 9000
        environment:
            - BACKEND=microservice_base_nginx
            - CONSUL=autodiscovery

    microservice_base_nginx:
        build: ./microservices/base/nginx/
        links:
            - autodiscovery
            - microservice_base_fpm
        environment:
            - BACKEND=microservice_base_fpm
            - CONSUL=autodiscovery
        ports:
            - 8080:80
            - 9090:9090
